# Generated by Django 4.2.3 on 2023-07-18 05:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='messageboard',
            name='school_class',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='messageboard',
            name='posts',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='messageboard',
            name='subject',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=255)),
                ('last_name', models.CharField(default='', max_length=255)),
                ('phone', models.CharField(default='', max_length=255)),
                ('city', models.CharField(default='', max_length=255)),
                ('type', models.CharField(default='', max_length=255)),
                ('parents', models.CharField(default='', max_length=255)),
                ('students', models.CharField(default='', max_length=255)),
                ('teachers', models.CharField(default='', max_length=255)),
                ('school_class', models.CharField(default='', max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
