# Generated by Django 4.2.3 on 2023-07-18 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_messageboard_school_class_alter_messageboard_posts_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messageboard',
            options={'ordering': ['subject']},
        ),
        migrations.RemoveField(
            model_name='messageboard',
            name='date_added',
        ),
    ]
