# Generated by Django 4.2.3 on 2023-07-18 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_remove_messageboard_posts_posts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='messageboard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post', to='main_app.messageboard'),
        ),
    ]
