# Generated by Django 4.2.3 on 2023-07-18 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_posts_messageboard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='messageboard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='main_app.messageboard'),
        ),
    ]
