# Generated by Django 4.2.3 on 2023-07-18 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_post_delete_posts'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messageboard',
            options={'ordering': ['topics']},
        ),
        migrations.RenameField(
            model_name='messageboard',
            old_name='subject',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='messageboard',
            name='school_class',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='school_class',
        ),
        migrations.AddField(
            model_name='messageboard',
            name='topics',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='message_board',
            field=models.ManyToManyField(to='main_app.messageboard'),
        ),
        migrations.CreateModel(
            name='SchoolClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(default='', max_length=255)),
                ('grade', models.CharField(default='', max_length=20)),
                ('school_type', models.CharField(default='', max_length=255)),
                ('user_profile', models.ManyToManyField(to='main_app.userprofile')),
            ],
            options={
                'ordering': ['school', 'grade'],
            },
        ),
    ]
