# Generated by Django 4.2.3 on 2023-07-18 23:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_remove_schoolclass_user_profile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='message_board',
        ),
        migrations.AddField(
            model_name='messageboard',
            name='school_class',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='messageboard', to='main_app.schoolclass'),
        ),
    ]
