# Generated by Django 4.2.3 on 2023-07-19 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_remove_userprofile_message_board_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='messageboard',
            field=models.ManyToManyField(default='', to='main_app.messageboard'),
        ),
    ]
