# Generated by Django 4.2.3 on 2023-07-19 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_remove_userprofile_messageboard_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messageboard',
            name='date_added',
        ),
        migrations.RemoveField(
            model_name='messageboard',
            name='user_profile',
        ),
        migrations.AddField(
            model_name='messageboard',
            name='user_profile',
            field=models.ManyToManyField(to='main_app.userprofile'),
        ),
    ]
