# Generated by Django 4.2.3 on 2023-07-19 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_remove_userprofile_school_class_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='school_class',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='school_class',
            field=models.ManyToManyField(blank=True, related_name='users', to='main_app.schoolclass'),
        ),
    ]
